CONEXION = red.dao.postgresql.ConexionPostgresqlDAO
EQUIPO = red.dao.postgresql.EquipoPostgresqlDAO
TIPOCABLE = red.dao.postgresql.TipoCablePostgresqlDAO
TIPOEQUIPO = red.dao.postgresql.TipoEquipoPostgresqlDAO
TIPOPUERTO = red.dao.postgresql.TipoPuertoPostgresqlDAO
UBICACIONES = red.dao.postgresql.UbicacionesPostgresqlDAO
